# Generated by Django 5.2 on 2025-04-10 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('datatype', models.CharField(max_length=8)),
                ('container', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('updated', models.DateTimeField()),
                ('term', models.ForeignKey(db_column='term_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terms.terms')),
            ],
            options={
                'db_table': 'fields',
                'managed': True,
            },
        ),
    ]
