# Generated by Django 5.2 on 2025-04-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'managed': True},
        ),
    ]
