# Generated by Django 5.2 on 2025-04-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.CharField(blank=True, max_length=8, null=True)),
                ('vocab', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('base', models.CharField(blank=True, max_length=128, null=True)),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
                ('subcontexts', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField()),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projects')),
            ],
            options={
                'db_table': 'contexts',
                'managed': False,
            },
        ),
    ]
