# Generated by Django 5.2 on 2025-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contexts',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
