# Generated by Django 5.2 on 2025-04-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        ('fields', '0002_alter_fields_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('context', models.ForeignKey(blank=True, db_column='context_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contexts.contexts')),
                ('field', models.ForeignKey(blank=True, db_column='field_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fields.fields')),
            ],
            options={
                'db_table': 'contexts_fields',
                'managed': False,
            },
        ),
    ]
