# Generated by Django 5.2 on 2025-04-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'managed': True},
        ),
    ]
