# Generated by Django 5.1.8 on 2025-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='headers',
        ),
        migrations.AddField(
            model_name='servers',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
