# Generated by Django 5.2 on 2025-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servers',
            options={'managed': False},
        ),
    ]
