# Generated by Django 5.2 on 2025-04-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_servers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servers',
            options={'managed': True},
        ),
    ]
