# Generated by Django 5.2 on 2025-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('ns', models.CharField(max_length=8)),
                ('path', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('homepage', models.CharField(blank=True, max_length=256, null=True)),
                ('trmcnt', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('updated', models.DateTimeField()),
                ('server', models.ManyToManyField(to='servers.servers')),
            ],
            options={
                'db_table': 'onts',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
