# Generated by Django 5.2 on 2025-04-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0002_alter_servers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ns', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('homepage', models.CharField(max_length=128)),
                ('trmcnt', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('updated', models.DateTimeField()),
                ('server', models.ForeignKey(db_column='server_id', on_delete=django.db.models.deletion.DO_NOTHING, to='servers.servers')),
            ],
            options={
                'db_table': 'onts',
                'ordering': ('name',),
                'managed': False,
            },
        ),
    ]
