# Generated by Django 5.2 on 2025-04-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onts',
            options={'managed': True, 'ordering': ('name',)},
        ),
    ]
