# Generated by Django 5.2 on 2025-04-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onts',
            old_name='server',
            new_name='servers',
        ),
    ]
