# Generated by Django 5.2 on 2025-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0002_rename_server_onts_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='onts',
            name='langs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
