# Generated by Django 5.1.8 on 2025-04-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0003_onts_langs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onts',
            name='langs',
        ),
        migrations.RemoveField(
            model_name='onts',
            name='version',
        ),
    ]
