# Generated by Django 5.2.1 on 2025-05-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onts', '0004_remove_onts_langs_remove_onts_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onts',
            old_name='path',
            new_name='url',
        ),
    ]
