# Generated by Django 5.2.1 on 2025-05-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
        ('onts', '0005_rename_path_onts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepts',
            name='ont_id',
        ),
        migrations.AddField(
            model_name='concepts',
            name='ont',
            field=models.ForeignKey(blank=True, db_column='ont_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onts.onts'),
        ),
    ]
