# Generated by Django 5.2.1 on 2025-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_remove_concepts_ont_id_concepts_ont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepts',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
